export const Left1=[
    {"article":" Ban Bí thư Trung ương Đảng chuẩn y nhân sự mới ",
    "link":"",
    "images":"/Zone1/News1.jpg",
    "para":"Ban Bí thư Trung ương Đảng chuẩn y đồng chí Nguyễn Quang Huy giữ chức Phó Chủ nhiệm Ủy ban Kiểm tra Tỉnh ủy Thừa Thiên Huế nhiệm kỳ 2020 - 2025."},
    {"article":"Ban Bí thư Trung ương Đảng chuẩn y nhân sự mới",
    "link":"",
    "images":"/SK1.jpeg",
    "para":"TPO - Ngày 23/11, theo thông tin PV nắm được, Bộ GD&ĐT đã có công văn gửi Trường ĐH Sư phạm Kỹ thuật TPHCM về việc thôi giữ chức vụ Chủ tịch Hội đồng trường đối với ông Ngô Văn Thuyên."},
    {"article":" Ban Bí thư Trung ương Đảng chuẩn y nhân sự mới ",
    "link":"",
    "images":"/Zone1/News1.jpg",
    "para":"Ban Bí thư Trung ương Đảng chuẩn y đồng chí Nguyễn Quang Huy giữ chức Phó Chủ nhiệm Ủy ban Kiểm tra Tỉnh ủy Thừa Thiên Huế nhiệm kỳ 2020 - 2025."},
    {"article":" Ban Bí thư Trung ương Đảng chuẩn y nhân sự mới ",
    "link":"",
    "images":"/Zone1/News1.jpg",
    "para":"Ban Bí thư Trung ương Đảng chuẩn y đồng chí Nguyễn Quang Huy giữ chức Phó Chủ nhiệm Ủy ban Kiểm tra Tỉnh ủy Thừa Thiên Huế nhiệm kỳ 2020 - 2025."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
]
export const Left2=[
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
]

export const Left3=[
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
    {"article":"Không khí lạnh cực đại tràn xuống Lào Cai, Sa Pa có thể rét 6-8 độ C",
    "link":"http://tienphong.vn/khong-khi-lanh-cuc-dai-tran-xuong-lao-cai-sa-pa-co-the-ret-6-8-do-c-post1395304.tpo",
    "images":"/Zone1/News1.jpgNews2.jpg",
    "para":"Ngày 23/11, Giám đốc Đài Khí tượng thủy văn tỉnh Lào Cai Lưu Minh Hải cho biết, không khí lạnh đang tăng cường xuống Lào Cai đạt ngưỡng cực đại, kéo theo nhiệt độ các khu vực ở địa phương sẽ giảm xuống mức thấp nhất trong đợt rét này."},
]
